name: 'github-extract-task-ids-action'
description: 'Extract task ids from commit messages, branch and pull request title using regular expressions'
author: 'Rexon'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  token:
    description: "Your Github token"
    required: true
  task_id_pattern:
    description: "The regex patteren of your task id"
    required: true
    default: '[A-Z]{2,}-[0-9]{1,5}'
  pull_number:
    description: "The pull request number"
    required: false